In [1]:
import numpy as np

In [4]:
# 类型不同会自动向上转换
np.array([1, 2, 3, 4, 4.3])

array([1. , 2. , 3. , 4. , 4.3])

In [5]:
# 多层list
np.array([range(i, i + 3) for i in range(10)])

array([[ 0,  1,  2],
       [ 1,  2,  3],
       [ 2,  3,  4],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11]])

In [7]:
shape = (3, 4)
np.zeros(shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones(shape)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.full(shape, 2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [11]:
np.random.random(shape)

array([[0.81578017, 0.13777607, 0.9235161 , 0.83331077],
       [0.03841893, 0.69446345, 0.23397084, 0.61339657],
       [0.10722824, 0.70101884, 0.78479654, 0.00196652]])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [16]:
np.random.normal(0, 1, shape)

array([[ 0.76124857,  0.86827951, -0.83242022, -1.24419171],
       [ 0.85631169, -0.0973811 ,  0.38337664, -0.52659035],
       [-0.66525568,  0.6956507 , -0.38987703, -1.07443774]])

In [17]:
# 未知值
np.empty(shape)

array([[0.76124857, 0.86827951, 0.83242022, 1.24419171],
       [0.85631169, 0.0973811 , 0.38337664, 0.52659035],
       [0.66525568, 0.6956507 , 0.38987703, 1.07443774]])

In [19]:
# n * n 的单位矩阵
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
e

NameError: name 'e' is not defined

In [22]:
lin = np.arange(5)

In [24]:
e^lin

NameError: name 'e' is not defined